//данные о продуктах
let all_products = {
    '1': {
        name: "Удон с говядиной",
        image: "Images/Catalog/Udon/1.png",
        classImg: "img1",
        price: 8.3,
        description: 'Лапша удон, морковь, <br> говядина, красный перец, <br> репчатый лук, чеснок, зеленый лук, <br> соевый соус, молотый имбирь',
    },
    '2': {
        name: "Удон с курицей",
        image: "Images/Catalog/Udon/2.png",
        classImg: "img2",
        price: 8.5,
        description: 'Лапша удон, морковь, <br> курица, красный перец, <br> репчатый лук, чеснок, зеленый лук, <br> соевый соус, молотый имбирь',
    },
    '3': {
        name: "Удон со свининой",
        image: "Images/Catalog/Udon/3.png",
        classImg: "img3",
        price: 8.4,
        description: 'Лапша удон, морковь, <br> свинина, красный перец, <br> репчатый лук, чеснок, зеленый лук, <br> соевый соус, молотый имбирь',
    },

    '4': {
        name: "Соба с говядиной",
        image: "Images/Catalog/Soba/1.png",
        classImg: "img4",
        price: 8.2,
        description: 'Говядина, лапша соба, <br> лук репчатый, морковь, <br> масло растительное, соевый соус, <br> томатная паста, паприка',
    },
    '5': {
        name: "Соба с курицей",
        image: "Images/Catalog/Soba/2.png",
        classImg: "img5",
        price: 8.4,
        description: 'Курица, лапша соба, <br> лук репчатый, морковь, <br> масло растительное, соевый соус, <br> томатная паста, паприка',
    },
    '6': {
        name: "Соба со свининой",
        image: "Images/Catalog/Soba/3.png",
        classImg: "img6",
        price: 8.3,
        description: 'Свинина, лапша соба, <br> лук репчатый, морковь, <br> масло растительное, соевый соус, <br> томатная паста, паприка',
    },

    '7': {
        name: "Роллы “Мидори”",
        image: "Images/Catalog/Sushi/1.png",
        classImg: "img7",
        price: 12.2,
        description: 'Нори, рис, тобико, <br> спайси соус, кунжут, <br> сухари японские, соус унаги',
    },
    '8': {
        name: "Роллы “Дракон”",
        image: "Images/Catalog/Sushi/2.png",
        classImg: "img8",
        price: 13.1,
        description: 'Рис, нори, лосось, <br> сыр, огурец, угорь, кунжут, <br> унаги соус, имбирь маринованный, <br> соевый соус, васаби',
    },
    '9': {
        name: "Роллы “Канада”",
        image: "Images/Catalog/Sushi/3.png",
        classImg: "img9",
        price: 11.7,
        description: 'Угорь, лосось, огурец, рис, <br> нори, унаги соус, кунжут',
    },

    '10': {
        name: "Суши “Сяке”",
        image: "Images/Catalog/Rolls/1.png",
        classImg: "img10",
        price: 10.2,
        description: 'Лосось, рис, <br> имбирь маринованный, васаби',
    },
    '11': {
        name: "Суши “Тамаго”",
        image: "Images/Catalog/Rolls/2.png",
        classImg: "img11",
        price: 10.9,
        description: 'Рис, нори, куриное филе, <br> специальный соус с икрой, кунжут',
    },
    '12': {
        name: "Суши “Унаги”",
        image: "Images/Catalog/Rolls/3.png",
        classImg: "img12",
        price: 11.5,
        description: 'Рис, нори, угорь, <br> соус унаги, кунжут',
    },

    '13': {
        name: 'Чизкейк из матчи',
        image: "Images/Catalog/Desserts/1.png",
        classImg: "img13",
        price: 5.6,
        description: 'Печенье, сливочное масло, <br> матча, сливочный сыр, греческий йогурт, <br> сахарная пудра, желатин',
    },
    '14': {
        name: "Моти с манго",
        image: "Images/Catalog/Desserts/2.png",
        classImg: "img14",
        price: 4.6,
        description: 'Мальтозный сироп, крахмал, <br> паста манго, питьевая вода, <br> клейкий рис, белый сахар, <br> кокосовое масло',
    },
    '15': {
        name: "Моти из матчи",
        image: "Images/Catalog/Desserts/3.png",
        classImg: "img15",
        price: 4.5,
        description: 'Мальтозный сироп, крахмал, <br> паста из матчи, питьевая вода, <br> клейкий рис, белый сахар, <br> кокосовое масло',
    },

    '16': {
        name: "Мороженое из чая",
        image: "Images/Catalog/Desserts/4.png",
        classImg: "img16",
        price: 5.4,
        description: 'Молоко, зеленый чай, сахар,<br> сгущенное молоко',
    },
    '17': {
        name: "Запеченный ролл",
        image: "Images/Catalog/Desserts/5.png",
        classImg: "img17",
        price: 8.3,
        description: 'Рис, киви, клубничный сироп, <br> хлопья',
    },
    '18': {
        name: "Панакота",
        image: "Images/Catalog/Desserts/6.png",
        classImg: "img18",
        price: 6.5,
        description: 'Вишня, сливки, молоко, сахар, <br> желатин',
    },

    '19': {
        name: "Онигири с креветками",
        image: "Images/Catalog/Onigiri/1.png",
        classImg: "img19",
        price: 5.4,
        description: 'Рис, креветки, <br> сыр плавленный, нори, майонез',
    },
    '20': {
        name: "Онигири с лососем",
        image: "Images/Catalog/Onigiri/2.png",
        classImg: "img20",
        price: 5.8,
        description: 'Рис, лосось, <br> сыр плавленный, нори, майонез',
    },
    '21': {
        name: "Онигири с овощами",
        image: "Images/Catalog/Onigiri/3.png",
        classImg: "img21",
        price: 5.5,
        description: 'Рис, огурцы, помидоры, <br> морковь, сыр плавленный, <br> нори, майонез',
    },
    '22': {
        name: "Онигири с икрой",
        image: "Images/Catalog/Onigiri/4.png",
        classImg: "img22",
        price: 6.3,
        description: 'Рис, красная икра, <br> сыр плавленный, нори, майонез',
    },
    '23': {
        name: "Онигири с курицей",
        image: "Images/Catalog/Onigiri/5.jpg",
        classImg: "img23",
        price: 6.2,
        description: 'Рис, курица, <br> сыр плавленный, нори, майонез',
    },
    '24': {
        name: "Онигири с форелью",
        image: "Images/Catalog/Onigiri/6.jpg",
        classImg: "img24",
        price: 6.8,
        description: 'Рис, форель, <br>  сыр плавленный, нори, <br>  майонез, красная икра',
    },

    '25': {
        name: "Вода",
        image: "Images/Catalog/Waters/1.png",
        classImg: "img25",
        price: 2.9,
    },
    '26': {
        name: "Газированная вода",
        image: "Images/Catalog/Waters/2.png",
        classImg: "img26",
        price: 2.9,
    },
    '27': {
        name: "Coca-Cola",
        image: "Images/Catalog/Waters/3.png",
        classImg: "img27",
        price: 3.5,
    },
    '28': {
        name: "Fanta",
        image: "Images/Catalog/Waters/4.png",
        classImg: "img28",
        price: 3.5,
    },
    '29': {
        name: "Sprite",
        image: "Images/Catalog/Waters/5.png",
        classImg: "img29",
        price: 3.5,
    },
    '30': {
        name: "Чай Lipton",
        image: "Images/Catalog/Waters/6.png",
        classImg: "img30",
        price: 3.2,
    },
};